### ISSUE TITLE
Exif parsing is incomplete

### ISSUE THREAD

**Issue by kmilos** [AOMediaCodec/libavif#1258]
The offset (which could be non-zero) is actually not used and stream not advanced far enough here:

https://github.com/AOMediaCodec/libavif/blob/main/src/read.c#L1485-L1491

The returned exif buffer can thus contain junk bytes at the beginning, with no way of retrieving back the offset value removed.

**Comment by y-guyon** [comment]
Thank you for your report. Do you have a reproducer file showing the issue?

The way I understand how this code block works:
1. It loads the full Exif payload to `exifContents`
2. It makes a `exifBoxStream` out of it
3. It discards the first 4 bytes belonging to the AVIF specification and not to the Exif specification (`exifTiffHeaderOffset`)
4. It copies all remaining bytes to `image->exif`

So I agree that some junk can be copied over before the actual Exif `MM\0\42` or `II\42\0` header tag. But it is the purpose of `avifGetExifTiffHeaderOffset()` to find that tag and to ignore the junk bytes. Usually we try not to mess around and modify too much metadata; if the user intended to keep these "junk bytes" at the beginning of `image->exif`, how can we be sure it is safe to discard? They are part of the AVIF file payload, and I think they should be returned by the libavif decoder API.

The most important feature I can think of is metadata lossless roundtrip: if you encode a slightly erroneous Exif chunk (one that begins with `Exif\0\0MM\0\42` for example), most users expect an error at encoding or the exact same metadata length and content at decoding. Silently modifying metadata is confusing.

We are left with either an error at encoding, which I think is overkill, or a new API feature to be able to fetch the `exif_tiff_header_offset` as it was stored in the AVIF file from the returned `avifImage`. I believe the latter may be considered if there was a strong use case that could not be easily solved by either `avifGetExifTiffHeaderOffset()`, libheif and/or a custom parser. Otherwise it is not worth polluting the libavif API in my opinion.

**Comment by kmilos** [comment]
Oops, I missed the `avifGetExifTiffHeaderOffset()` call, sorry (and implemented something similar by hand).

So the API is, in a sense, complete and there is no error per se, so please feel free to close if you wish to do so.

It's not very efficient though unfortunately, as the parsed O(1) offset would allow to skip this O(n) search...

**Comment by y-guyon** [comment]
> It's not very efficient though unfortunately, as the parsed O(1) offset would allow to skip this O(n) search...

I agree. There are usually only a few "junk bytes" though, and the O(n) search is insignificant compared to the whole sample decoding process.
