### ISSUE TITLE
Link-U testfiles stopped working

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#131]
Today I tried libavif from git and observed that I am no longer able to open Link-U testfiles.
For example:
https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/kimono.avif
`ERROR: Failed to parse input: No AV1 items found`

I am able to open AVIF files created via libavif in the past.

**Comment by novomesk** [comment]
Unable to open Summer_in_Tomsk_720p_5x4_grid.avif
I get "Invalid image grid" error now.

**Comment by joedrago** [comment]
Hmm, good catch. I imagine this is due to @cconcolato 's recommendation to bail out when libavif detects an item property it "ignores" but the property is flagged as `essential`. I'll see what I'm missing in those files and fix it.

**Comment by joedrago** [comment]
This should fix it:

https://github.com/AOMediaCodec/libavif/commit/604215614f2509c152e0313606a675899e4fff1c

I wasn't parsing the `pixi` item property because the depths in there are semi-redundant (the guaranteed-to-be-correct depth comes from the AV1 decoder, and the containerDepth is pulled from the av1C block), but pixi is flagged as essential, so I must properly parse it.

I'm now parsing it and verifying that the box contents are "valid" (to be parsed), and those images you cited appear to decode just fine now. Let me know if you run into any other weird ones.

**Comment by cconcolato** [comment]
Actually, I think the files are wrong. The essential bit should not be set on `pixi`. It is a descriptive property and descriptive properties cannot be essential (unless indicated otherwise in the spec, eg. codec configuration).
