### ISSUE TITLE
which library should be used for android ？

### ISSUE THREAD

**Issue by Buxiaohui** [AOMediaCodec/libavif#1326]
Hi，I have a question，I am an android engineer, when compiling libavif locally, I saw the default decoding library is LIBGAV1, Is that because LIBGAV1 is the best for android ？  why not aom or dav1d？

**Comment by vigneshvg** [comment]
> I saw the default decoding library is LIBGAV1, Is that because LIBGAV1 is the best for android ？ 

We just provide build instructions for `libgav1` as an example in order to make the decoding work on android. If you want a production version, `libavif` is hosted on maven central here: https://repo1.maven.org/maven2/org/aomedia/avif/android/avif/

> why not aom or dav1d？

`aom` decoder is notoriously slow and is not recommended for production use. The maven hosted version of `libavif` uses `dav1d` as the decoder. It also bundled `libyuv` for faster color conversion.
