### ISSUE TITLE
Move iccjpeg.c out of avifjpeg.c to a separate file

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#136]
In v0.7.0, iccjpeg.c from http://www.littlecms.com/1/iccjpeg.c was copied into apps/shared/avifjpeg.c. Since iccjpeg.c has its own open-source license, it is better to copy iccjpeg.c and iccjpeg.h as separate files, similar to how cJSON.c and cJSON.h were copied, so that each file contains code under a single open-source license. The license of iccjpeg.c and iccjpeg.h should be appended to the LICENSE file.

This will also allow a libavif client to use their own copy of iccjpeg.c and iccjpeg.h.

Note: The http://www.littlecms.com/1/iccjpeg.c URL returns an HTTP 404 error right now.

**Comment by joedrago** [comment]
I went and grabbed the latest lcms2-2.9 source archive and pulled the `iccjpeg.*` files from there, along with the license file. I had to re-add the `volatile` tag to avoid `-Werror=clobbered` on gcc, and I chose to prefix it with `avif_` to make it clear it was a "new thing", but otherwise it is the original file. I also pasted the contents of `LICENSE_iccjpeg` to the bottom of my `LICENSE` file.

Is this commit what you had in mind? If so, I can put it in master.

https://github.com/AOMediaCodec/libavif/commit/9a12da1aee4b0e479393ba35a3a7bd9426e5ecd1

**Comment by wantehchang** [comment]
Joe: Thanks! Let me take a look now.

**Comment by joedrago** [comment]
I liked your comments, so I implemented them. I now disable `-Wclobbered` in those two files specifically, use the original `iccjpeg.*` names, and include `libjpeg.h` explicitly.

https://github.com/AOMediaCodec/libavif/commit/9d60be2540f812de350be7195054598b3e67fb64
