### ISSUE TITLE
libavif why not set AVIF_LIBYUV_ENABLED default true

### ISSUE THREAD

**Issue by WizzXu** [AOMediaCodec/libavif#1485]
libyuv can make image scale , and why not set AVIF_LIBYUV_ENABLED true default?
How can I make avifimage scale on Android JNI?
Thank you very match

**Comment by jzern** [comment]
Detection of libyuv is [enabled by default](https://github.com/AOMediaCodec/libavif/blob/cef074c8250f01f4a3dce8e9ff2314dd4372c40a/CMakeLists.txt#L159). If it's found, `AVIF_LIBYUV_ENABLED` will be defined. The code was reworked a little since `v0.11.1`, but detection should work in that release as well.

`AVIF_LOCAL_LIBYUV` can also be used to use a local build of the library.
