### ISSUE TITLE
ERROR: Failed to decode frame: Decoding of color planes failed

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#1725]
Hello,

One user sent me an AVIF image [image.zip](https://github.com/AOMediaCodec/libavif/files/13259619/image.zip) .

That image works in Chrome but doesn't work in Firefox. Some people are able to open it in KDE apps, some doesn't, depending on libavif configuration.

```
avifdec -i DSC02464.avif 
Image decoded: DSC02464.avif
 * Resolution     : 2832x4240
 * Bit Depth      : 8
 * Format         : YUV420
 * Chroma Sam. Pos: 0
 * Alpha          : Absent
 * Range          : Full
 * Color Primaries: 2
 * Transfer Char. : 2
 * Matrix Coeffs. : 6
 * ICC Profile    : Absent
 * XMP Metadata   : Absent
 * Exif Metadata  : Present (48216 bytes)
 * Transformations:
    * irot (Rotation)      : 1
 * Progressive    : Unavailable
 * 1 timescales per second, 1.00 seconds (1 timescales), 1 frame
 * Frame:
ERROR: Failed to decode frame: Decoding of color planes failed
Diagnostics:
 * avifImageScale() called, but is unimplemented without libyuv!
```

Can you take a look and suggest what can be done to improve the situation?

**Comment by novomesk** [comment]
File was created using older libheif. libheif from git creates AVIF files where the width and height is not swapped, so it works correctly in other implementations.

**Comment by y-guyon** [comment]
Thanks for your report and investigation.

> ` * Resolution     : 2832x4240`

The AV1 frame is a portrait picture of a narrow street, rotated by 90 degrees clockwise.

Using [mp4box.js](https://gpac.github.io/mp4box.js/test/filereader.html), the `ispe` property indeed indicates a width of 2832 and a height of 4240.  
There also is an `irot` property with `angle=1` (90 degrees anti-clockwise).   
ISO 23008-12 says:  
> The `ImageSpatialExtentsProperty` documents the width and height of the associated image item. Every image item shall be associated with one property of this type, prior to the association of all transformative properties.

Rotation being applied after spatial extents (scaling), the attached AVIF file is incorrect (it renders stretched in Chrome).  
Switching the width and height in the `ispe` box fixes it (no scaling performed).

There is also Exif metadata, probably containing rotation information, which should be ignored by AVIF decoders (only `irot` is meaningful in HEIF).

Please note that `avifdec` will not rotate the image when requesting PNG output ([not yet implemented](https://github.com/AOMediaCodec/libavif/pull/1186#discussion_r1004566886)), but will copy the Exif chunk with the rotation metadata which should not be applied according to the PNG specification.

> `avifImageScale() called, but is unimplemented without libyuv!`

Please note that libyuv could be bundled, and when impossible, libavif now has a workaround since 808bf58 (see https://github.com/AOMediaCodec/libavif/issues/709).

> Can you take a look and suggest what can be done to improve the situation?

So either adding the libyuv dependency or updating libavif should work for decoding these files generated with an older version of libheif. But these files should be rendered as landscape (stretched) according to the specification, so fixing the files is the priority.

Feel free to request further assistance.
