### ISSUE TITLE
[discussion] why not using only dav1d for decoding ?

### ISSUE THREAD

**Issue by vtorri** [AOMediaCodec/libavif#201]
according to this recent benchmark : 

https://docs.google.com/spreadsheets/d/1kGls7Pd9ZhALb5I5T_JVhRXzp-wmSzSyEBPWJi0X93s/edit#gid=1894017530

dav1d is a lot faster than aom or gav1, so I think that for just a frame, it is the same

this will simplify a lot the cmake stuff imho

**Comment by 1480c1** [comment]
Personally, the only reason I could see someone using libaom for decoding is for conformance, performance, or some other test with the exception of if your OS or distro doesn't have a libdav1d package, like ubuntu others. I'm not sure if there's a good use case or reason to use libgav1 just yet due to performance compared to libdav1d even on libgav1's targeted platform arm

**Comment by joedrago** [comment]
The goal is choice. libgav1 decoding might find a home on Android, others might already have a pre-existing library on their device and not want to bother incorporating a second library. I plan to support more codecs in the future (SVT, etc). It is easy enough to disable them for any of your personal projects, or enforce the usage of a single path (avifCodecChoice).

**Comment by novomesk** [comment]
I my own test on PC, dav1d was slower in 10/12 bit decoding than libaom.
dav1d is good for 8bit input.

**Comment by joedrago** [comment]
Closing this as I don't plan on removing support for any existing codec paths.
