### ISSUE TITLE
Shared Library support

### ISSUE THREAD

**Issue by darix** [AOMediaCodec/libavif#22]
Is there any reason why there is no support yet?

would patches be welcome for it?

**Comment by darix** [comment]
and while we are at it ... "make install" target would be nice.

**Comment by joedrago** [comment]
Interesting, I thought I had done that a while ago, but it turns out I hadn't! 

I've removed the overly-opinionated STATIC keyword from the add_library call, and some fairly basic/obvious install() calls. I believe with judicious usage of `BUILD_SHARED_LIBS`, `AVIF_CODEC_*`, and `ninja install`, you should be able to make any kind of build recipe you want.

Let me know if something is missing and I can add it. I'm not opposed to patches either.
