### ISSUE TITLE
gtest/avif_fuzztest_helpers.cc is compiled once for each fuzztest target

### ISSUE THREAD

**Issue by wantehchang** [AOMediaCodec/libavif#2358]
In tests/CMakeLists.txt, the `add_avif_fuzztest` macro is defned as follows:

```
    macro(add_avif_fuzztest TEST_NAME)
        add_executable(${TEST_NAME} gtest/${TEST_NAME}.cc gtest/avif_fuzztest_helpers.cc ${ARGN})
        ...
```

I think this means gtest/avif_fuzztest_helpers.cc is compiled once for each fuzztest target. We should move it to an object or static library so that it is compiled only once for all fuzztest targets.

**Comment by vrabaud** [comment]
I had not done so because this requires calling `link_fuzztest` on the object library and that function is totally opaque (e.g. it might just work on a binary). Luckily, all it does is calling `target_link_libraries`, cf https://github.com/google/fuzztest/blob/02daa2ab69f514109c8831d72a13ffab49f6f375/cmake/AddFuzzTest.cmake#L1

Feel free to approve https://github.com/AOMediaCodec/libavif/pull/2417 to get a solution that works until `link_fuzztest` does not change behavior.

**Comment by vrabaud** [comment]
Fixed by https://github.com/AOMediaCodec/libavif/pull/2417
