### ISSUE TITLE
android jni compile

### ISSUE THREAD

**Issue by wzes** [AOMediaCodec/libavif#2390]
I use the main branch androidjni to compile the products with libavif_android.so and libyuv.so files, but there is no libyuv.so in the maven repo avif-1.0.1.262e11d, and the aar size is relatively large. What is the reason?

**Comment by vigneshvg** [comment]
> I use the main branch androidjni to compile the products with libavif_android.so and libyuv.so files, but there is no libyuv.so in the maven repo avif-1.0.1.262e11d,

The maven hosted repo does have the necessary libyuv functions, but it is bundled inside `libavif_android.so` (just like there is no explicit `libdav1d.so` since that is also bundled within `libavif_android.so`).

>  and the aar size is relatively large. What is the reason?

The aar size is large because it contains the optimized versions of the underlying libraries (dav1d and libyuv) for all the supported Android architectures (arm, arm64, x86 and x86_64). In Android parlance, this is known as a "fat apk" [1][2].

If you targeting only a smaller set of devices with a known ABI, then you can reduce the binary size by only including the code necessary for that architecture. However we cannot support this in the maven hosted version and you would have to build it manually.

[1] https://en.wikipedia.org/wiki/Fat_binary
[2] https://developer.android.com/ndk/guides/abis

**Comment by wzes** [comment]
@vigneshvg How to package libyuv.so into libavif_android.so ？

**Comment by vigneshvg** [comment]
> @vigneshvg How to package libyuv.so into libavif_android.so ？

i am not sure how to do that under the gradle/cmake system off the top of my head. we use internal bazel build toolchain to generate the maven artifacts.

the idea is to build everything as a statically linked library so that it produces only one shared object in the end.

**Comment by jzern** [comment]
To do this manually one can use the `--whole-archive` linker option, e.g., `ld -shared -o shared.so --whole-archive archive1.a archive2.a ... --no-whole-archive`
