### ISSUE TITLE
supported_gainmap_writer_version_with_extra_bytes.avif is invalid

### ISSUE THREAD

**Issue by leo-barnes** [AOMediaCodec/libavif#2391]
@maryla-uc
I notice that supported_gainmap_writer_version_with_extra_bytes.avif is not actually a valid tmap file. The ispe property associated with the tmap has width and height set to 0.

      [ 8] ('ispe' "Image Spatial Extents", size = 20, offset = 493) {
        Version: 0, Flags: 0x000000
        Image Width: 0
        Image Height: 0
      }

**Comment by leo-barnes** [comment]
The `tmap` is also missing a `pixi`. This is not mandated as necessary by the spec, but is a nice to have.

**Comment by leo-barnes** [comment]
Ah. And another issue. The `altr` group ID is the same as the base item ID. Group and item ID's are not allowed to have collisions.

**Comment by leo-barnes** [comment]
The `ispe`, `pixi` and ID collision issues are present in all of the files.

For `unsupported_gainmap_minimum_version.avif` there is an additional issue in that the `minimum_version` (99) is greater than `writer_version` (0). I'm not sure if the spec explicitly states that `minimum_version <= writer_version`, but having it be the opposite doesn't really make sense.

**Comment by wantehchang** [comment]
Leo: Thank you very much for inspecting the test files and reporting the issues!

ISO/CD 21496-1 says:

> `writer_version` is the version of the metadata structure used by the writer. This shall be greater than
or equal to `minimum_version`.

libavif enforces this requirement:

```
    uint16_t writerVersion;
    AVIF_CHECKERR(avifROStreamReadU16(&s, &writerVersion), AVIF_RESULT_INVALID_TONE_MAPPED_IMAGE); // unsigned int(16) writer_version;
    AVIF_CHECKERR(writerVersion >= minimumVersion, AVIF_RESULT_INVALID_TONE_MAPPED_IMAGE);
```

The file name "unsupported_gainmap_minimum_version.avif" suggests that this test file is intended to test how the application handles an unsupported minimum_version. I wonder if Maryla generated the file so that it could be used to test the handling of two error conditions. Her [notes for this test file](unsupported_gainmap_minimum_version.avif) says:

> Contains a gain map with the `minimum_version` field set to 99 in the tmap box. `version` and `writer_version` are 0.

Since the current supported `minimum_version` is 0, any test file with the `writer_version < minimum_version` error will necessarily also has an unsupported `minimum_version`. I agree it is less confusing to set `writer_version = minimum_version = 99` in this file so that this file has only one error.

**Comment by maryla-uc** [comment]
Thanks a lot for pointing out these issues! I will send some fixes.

**Comment by maryla-uc** [comment]
The test files should be good now
