### ISSUE TITLE
Allow to use aom just for encoding

### ISSUE THREAD

**Issue by ePirat** [AOMediaCodec/libavif#254]
Currently trying to build libavif with aom that is built without decoder, it fails:

```
../src/codec_aom.c:14:10: fatal error: 'aom/aom_decoder.h' file not found
#include "aom/aom_decoder.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

It would be useful if this would work to reduce binary size of libaom when it is anyway only used for encoding because another decoder is preferred.

**Comment by jakearchibald** [comment]
fwiw, we had to 'ignore missing symbol' warnings when we built libavif for squoosh.app, so we could separate the encoder and decoder.

**Comment by RReverser** [comment]
@jakearchibald Heh, I came here to create an issue for this too and was going to tag you, but found this one already :)

To authors: FWIW, this should apply for "just decoding too". Generally, the problem seems to arise from the way various codecs are represented in code. Currently they're defined as a single object with pointers to encode and decode functions:

https://github.com/AOMediaCodec/libavif/blob/3fcc555000fffc3172db4c19c412eea7fb1d46a3/src/codec_aom.c#L613-L626

Instead, if code is refactored to allow creating encoder and decoder parts of each codec separately, then most compilation errors should go away and optimizers would be able to strip away the dead parts of code more easily.

**Comment by joedrago** [comment]
This use-case wasn't really a thought in my initial design, of course, and `libaom` is the only current outlier as far as the issue here. I'd prefer to not rearchitect libavif to handle this exceptional case (libaom), but I'd be on board with some additional `AVIF_` CMake options / `#defines` which would disable the AOM encoder and/or decoder. This should buy you the functionality you're looking for.

**Comment by RReverser** [comment]
> but I'd be on board with some additional AVIF_ CMake options / #defines which would disable the AOM encoder and/or decoder

What would it do when some code path accidentally does try invoke the disabled encoder or decoder though?

I wonder if it's both easier and more reliable to split AOM into two "codecs" here

https://github.com/AOMediaCodec/libavif/blob/0a0547b366dee71788285f724f9a725cb0aa7a5e/src/avif.c#L472-L474

where one item would be with `AVIF_CODEC_FLAG_CAN_DECODE` and another item would be with `AVIF_CODEC_FLAG_CAN_ENCODE`, but both would essentially refer to the same implementation.

This way, user could choose the parts they want to opt-in into, and any part of libavif would know whether encoder or decoder is enabled even without new extra flags.

**Comment by joedrago** [comment]
The definitions would block including the associated encoder/decoder headers in `codec_aom.c`, so I don't think there is much chance for that. I'd have to see how that block in `avif.c` would shake out as I implemented the new defines.

**Comment by RReverser** [comment]
> The definitions would block including the associated encoder/decoder headers in `codec_aom.c`

Ah yeah, that's a good point, it still wouldn't work out without splitting up in that case. I shall leave it to you then 😀

**Comment by joedrago** [comment]
Alright, I took a swing at it. 

In `master` right now, if you enable `AVIF_CODEC_AOM` like normal you can then explicitly _disable_ one of these, like so:

* `-DAVIF_CODEC_AOM_ENCODE=0`
* `-DAVIF_CODEC_AOM_DECODE=0`

This should not only avoid linking in and advertising whatever path you've disabled, but `avifCodecVersions()` should signal that libaom is only offering one of the two paths now. Give it a shot and let me know if I've missed something. It is going through CI now.

**Comment by RReverser** [comment]
Thanks, I'll give it a try. Do you think I still need to use `-DCONFIG_AV1_DECODER=0` / `-DCONFIG_AV1_ENCODER=0` when building AOM in this scenario as well, or LibAVIF will not reference the unnecessary parts anyway when `-DAVIF_CODEC_AOM_*=0` is used?

**Comment by joedrago** [comment]
I would build `libaom` in the leanest way possible for now, just to see if anything is sneaking its way into your build via libavif. If your app using `libavif` fails to link because you build `libaom` that way, that is a good hint to me that I missed something.

**Comment by RReverser** [comment]
Sounds reasonable, let me do a quick check...

**Comment by RReverser** [comment]
Encoder seems to build fine, but decoder built with `-DAVIF_CODEC_AOM_ENCODE=0` failed:

```
dec/avif_dec.cpp:19:29: error: no matching function for call to 'avifDecoderRead'
  avifResult decodeResult = avifDecoderRead(decoder, image, &raw);
                            ^~~~~~~~~~~~~~~
node_modules/libavif-dec/include/avif/avif.h:689:12: note: candidate function not viable: requires 2 arguments, but 3 were provided
avifResult avifDecoderRead(avifDecoder * decoder, avifImage * image); // call avifDecoderSetIO*() first
           ^
1 error generated.
```

Looking into why...

**Comment by joedrago** [comment]
That is simply that `v0.8.2` had a breaking change with that API to allow for streaming readers. The simplest fix here is to just change that call to `avifDecoderReadMemory()`, such as:

```
  avifResult decodeResult = avifDecoderReadMemory(decoder, image, raw.data, raw.size);
```

**Comment by joedrago** [comment]
Also (as the headers say), the `Read()` functions do additional image copies to avoid dependence on their associated `avifDecoder`. If you don't mind keeping your `avifDecoder` object around for the lifetime of the image itself, it is faster to break your decode into two calls (`avifDecoderParse()` and `avifDecoderNextImage()`) and simply use the decoder's avifImage itself (`decoder->image`). This should save on memcpys and memory overhead in general.

**Comment by RReverser** [comment]
> The simplest fix here is to just change that call to `avifDecoderReadMemory()`, such as:

Ah, right, that worked, thanks! So the new options seem to work.

Not strictly related, but while we're here, do you think it would be possible to also accept a path to the locally built AOM via CMake params as well?

Right now, in order to build separate encoder and decoder with `AVIF_LOCAL_AOM=1`, we have to actually create two copies of the directory structure - one `libavif-enc` and another `libavif-dec` - just so that each of them has own copy of `libavif-{enc,dec}/ext/aom` which `AVIF_LOCAL_AOM` expects.

However, the sources in both cases are the same and it's only the flags (`-DCONFIG_AV1_DECODER=0` / `-DCONFIG_AV1_ENCODER=0`) that differ between the two builds.

It would be much more convenient if there was a way to use a single source directory `libavif` and only provide it twice with different CMake folders built from the same `aom` source.

**Comment by RReverser** [comment]
> If you don't mind keeping your `avifDecoder` object around for the lifetime of the image itself, it is faster to break your decode into two calls (`avifDecoderParse()` and `avifDecoderNextImage()`) and simply use the decoder's avifImage itself (`decoder->image`). This should save on memcpys and memory overhead in general.

Interesting. I think we were just following the official example here:

https://github.com/AOMediaCodec/libavif/blob/dbfc61aa7e62cc1a24d1bcf2c8787ecd91731f65/examples/avif_example1.c#L75

Perhaps it's worth updating it or providing a separate one with the alternative approach?

**Comment by joedrago** [comment]
I'd prefer to not make the `AVIF_LOCAL_` hacks any more convoluted than they already are, but I'll think about it.

The examples in the README and the `examples/` directory are forever-slated to be rewritten, and I'm tracking the re-do here (#384). It is just work that hasn't been (re-)done yet, and my Real Life / Actual Work priorities are constantly overriding "re-do libavif examples". I'll see if I can at least do enough of a rework of README/examples next week simply to avoid people falling into a pseudo-trap of inefficiency with functions like Read.

**Comment by RReverser** [comment]
> I'd prefer to not make the `AVIF_LOCAL_` hacks any more convoluted than they already are, but I'll think about it.

Yeah I can understand the unwillingness to do that, it's just that as a result it feels like the burden of implementing said hacks gets moved onto the consumers of the library. I had to do some scary things in our Makefile to work around the expected directory structures, and it's still much more inefficient than it could be with a single source directory.

Either way, thanks for implementing the flags above - that already helps a lot :)

**Comment by joedrago** [comment]
Instead of making `AVIF_LOCAL_` the end-all-be-all of "how to embed libavif", I'd prefer we came up with other mechanisms. For example, I recently put in a subtle change to `Findlibyuv.cmake` here:

https://github.com/AOMediaCodec/libavif/commit/074ab284aebdf4d7052a03a593f246f65ddb2be8#diff-1fae1ad62f6cc5f5c7f479b56688b728f831387b7be4896d6ce123328e77f682

The check here is completely benign in the most common case (a normal *nix style build looking for libraries somewhere in the system), but if `libavif` is a child project inside of some parent CMake project, the parent project can actually pre-set the `LIBYUV_INCLUDE_DIR` and `LIBYUV_LIBRARY` variables and `libavif` will _magically_ find them using the normal CMake find mechanisms.

I'd be on board with making similar benign changes to the other CMake Find modules libavif uses if it allows for downstream projects to pre-seed the CMake environment with whatever paths they want libavif to find. This is much more preferable to me than further complicating the `AVIF_LOCAL_` hacks, which are really just there to make simple Windows builds and CI not awful.

**Comment by RReverser** [comment]
Yeah, a change like that would allow providing a path to LibAOM via variables too, so it's more or less the same as I was asking for :) The system search doesn't work / doesn't make sense for us in an Emscripten build, but anything that allows to specify a path would be great.

**Comment by joedrago** [comment]
See if similar local hacks in the adjacent CMake Find modules (in libavif) bear fruit for you. If so, hit me with a PR. :-)

**Comment by RReverser** [comment]
Sgtm, thanks! Meanwhile, I suppose this issue can be marked as resolved thanks to the flags above.

**Comment by RReverser** [comment]
Oh, just FYI - looks like those `if (NOT ...)` from the diff above are not even necessary, CMake already skips `find_*` steps if a variable is already set.

I just tried and found that I can remove `-DAVIF_LOCAL_AOM=1` and manually provide `-DAOM_LIBRARY=...path...` and `-DAOM_INCLUDE_DIR=...path...` and it works without any changes to `Findaom.cmake`.

So that's sorted too, then.

**Comment by joedrago** [comment]
Excellent. I decided to take 45 minutes just now and throw away the super-stale README examples, and put in some basic (actually compiled) examples in the `examples/` dir. I'm sure I'll be touching them up over the next week or so, but hopefully they'll help bootstrap fresh libavif users instead of the nonsense I had before.
