### ISSUE TITLE
AVIF with transparency created by libheif

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#280]
Please take a look at following issues:
https://bugs.chromium.org/p/chromium/issues/detail?id=1115483
https://github.com/strukturag/libheif/issues/279

AVIF with transparency created via libheif (heif-enc tool) is displayed incorrectly in libavif based applications.

**Comment by joedrago** [comment]
I'm not sure what the commandline was that created that file, but as @wantehchang points out in the Chromium thread, the U and V planes in the primary item are all 128, which means the image is just grayscale. Something during the encoding is eliminating chroma, and I'd be quite surprised if something can decode this specific AVIF file into its original colors, seeing as there isn't any interesting chroma in there.

**Comment by diemmarkus** [comment]
ok thanks! I guess we'll be fine to close the issue here and in nomacs since it seems to be related to libheif's encoding rather than decoding...

**Comment by farindk** [comment]
Issue has been resolved on our side. Problem was that the aom encoder state was not correctly reset between encoding the color and alpha images. Hence we ended up with both images concatenated in one stream. That's why it was still decoded correctly on our side (picking the "correct" image from the two).

This issue can be closed.

**Comment by novomesk** [comment]
Thanks all for investigating.
