### ISSUE TITLE
16-bit limited range constants are suspicious

### ISSUE THREAD

**Issue by kornelski** [AOMediaCodec/libavif#302]
Studio range min/max values for 16-bit samples don't look correct. The 1024 lower bound is suspiciously low (16*256+16 = 4112), probably got same 4x increase as 10 to 12 bit jump.

Upper 60160 corresponds to `235*265`, but that's not a good way to scale to a 16-bit range, since `255*256` is 0xFF00, rather than 0xFFFF.

https://github.com/AOMediaCodec/libavif/blob/5b32ce1f84e4de841b9bc046e84a353ba0af260d/src/reformat.c#L1055

**Comment by joedrago** [comment]
It is possible they are incorrect, but I believe those case statements are just in there for completeness, and I don't believe you can actually achieve 16bpc limited range in any code flow libavif offers. We can probably just remove those cases.

**Comment by wantehchang** [comment]
The first argument is incorrect:

```
        case 16:
            LIMITED_TO_FULL(1024, 61440, 65535);
            break;
```

The first argument should be (1 << (16 - 8)) * 16 = 4096.

Note: The second argument is (1 << (16 - 8)) * (219 + 16) = 60160, which is correct. These two arguments are calculated using Equation 23 in Section 8.3 (Matrix coefficients) of ITU-T H.273 (12/2016).

Joe, would you like me to fix this or just remove this? I would prefer to remove the 16bpc case.

**Comment by joedrago** [comment]
I think removing it is the better play as well.

**Comment by wantehchang** [comment]
[Note: I deleted an earlier version of this comment because I copied the 16bpc case from the wrong function. This is why Joe's answer appears before my question.]

The first argument is incorrect:

```
        case 16:
            LIMITED_TO_FULL(1024, 60160, 65535);
            break;
```

The first argument should be (1 << (16 - 8)) * 16 = 4096.

Note: The second argument is (1 << (16 - 8)) * (219 + 16) = 60160, which is correct. These two arguments are calculated using Equation 23 in Section 8.3 (Matrix coefficients) of ITU-T H.273 (12/2016).

Joe, would you like me to fix this or just delete this? I would prefer to just delete the 16 bpc case.
