### ISSUE TITLE
YUV->RGB conversion

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#309]
I have a test JPG which is grayscale looking. I GIMP I see `808080` RGB values.

When I encode it via avifenc (Matrix Coeffs. : 6) and convert to PNG (via avifdec), the values are `817f81`

There is a non-zero choma during decoding. It seems that zero chroma is encoded to 128 value. I have impression that during decoding, zero chroma is mapped to 127.5f (half of 255.0), so 128 value is deemed as non-zero chroma.

Is this behavior correct, desired, expected?

I am thinking if we use MC=6 (like JPG) conversion, we should get like-JPG results.

I am worried that different AVIF implementations use different calculations in RGB<->YUV. And using different combinations of implementations (different to encode and another to decode) can lead to bigger difference than 1 value per channel.

**Comment by novomesk** [comment]
I tried to use [davif](https://github.com/link-u/davif) and decoded values were `808080` (avifdec output `817f81` from the same file).

**Comment by joedrago** [comment]
My guess is somewhere there is a disconnect in the coefficients. Can you supply the file? I will look into this today.

**Comment by novomesk** [comment]
[testset.zip](https://github.com/AOMediaCodec/libavif/files/5211158/testset.zip)
808080.jpg - source
`avifenc -y 420 --min 0 --max 0 -s 5 -r f --ignore-icc --nclx 1/13/6 808080.jpg encoded.avif`
`avifdec encoded.avif decoded.png`

decoded.png has 817f81 values.

**Comment by joedrago** [comment]
I've diagnosed the issue and I'm working on a fix.

**Comment by joedrago** [comment]
Alright, so the issue here is that I was doing my UV biases in floating point space, so I was using a "true 0.5" for biasing, which is not common practice. `128/255` is actually `~0.502`, `512/1024` is actually `~0.5004`, etc. In order for gray to stay gray, the 0.5 bias must stay precise, so it must occur in integer space, which is what `davif` does, and now what `libavif` does. 

Please exercise the latest commit and see if it behaves more in-line with what you expect.
