### ISSUE TITLE
Suggestion: increase version number in master when there is breaking change

### ISSUE THREAD

**Issue by novomesk** [AOMediaCodec/libavif#368]
Hello Joe,
You usually increase version number in `include/avif/avif.h` and `CMakeLists.txt` right before new release.

I would like to have possibility to distinguish between between released version and a fresh snapshot from master.

For example last released version is 0.8.1
Master is also at version 0.8.1 but there are breaking changes in API.

If I detect 0.8.1 version I don't know if I am using the older API or newer API. If I can reliably detect those two, I had a chance to make a code which compile successfully on both.
In case of new breaking changes in master, I need the version number in master to be different than latest release.

**Comment by joedrago** [comment]
I would honestly prefer to not provide any support for untagged releases built directly out of a branch. The whole goal of versioning and tagging the release is to signal that the next round of changes are ready to be used in the field. If I started working in some other branch ("future", say) and did the same pattern, people would just start building the future branch instead to mess around with the latest code. If I preemptively bumped the version every time I changed anything, we'd just flood the history with a bunch of semi-broken versions.

I appreciate people testing master locally, but I would prefer people just waited for the next tagged release before putting it in any kind of distribution. If I didn't tag it with a version, it doesn't really exist yet.

**Comment by novomesk** [comment]
Unreleased versions are not a problem for me.
For example GIMP released 2.10.22 and they immediately made "post-release version bump to 2.10.23" afterwards.
2.10.23 is work in progress for developers and the future version for distribution will be probably 2.10.24.

Let's close, I respect your decision.

**Comment by joedrago** [comment]
Cool. For what it's worth, I'm wasn't trying to dismiss your request without thinking about it or anything. However, libavif needs a place for "not quite completed" changes. For example, I wrote `avifIO` maybe two weeks ago, and since then, I've made at least 4-5 breaking changes to its API due to feedback from various contributors (removal of the `FILE*` API, changing return values on some of the signatures, etc).

In ancient times before DVCS "won", I could have put something like exposing the Perforce commit number in some constant, but it'd create this weird soup of #ifdefs in early-adopter code, where people were going to try to support API signatures that only lived for 4 days and were never a part of any official release. I'm much happier letting things reach a new point of stability, surviving `oss-fuzz` for a while, and a thorough Chrome code review (thanks to Wan-Teh) before putting any kind of versioned stamp-of-approval on it. 

Perhaps the middle ground here is really "please make releases more often", which I can do. It is only when I make these larger changes (like `avifIO`) that I need to tread with caution.

**Comment by joedrago** [comment]
As a note, I just released `0.8.2`, so whatever issue you're having right now should hopefully be helped with that.

**Comment by novomesk** [comment]
Thanks for the new version! It helps me. I was guessing it will be 0.9.0 because of the big changes with the reader API.

**Comment by joedrago** [comment]
Hi @novomesk -- I thought a lot about this issue of being able to link against "in-development" versions of `libavif` without breaking your stable builds, and I've just introduced a change today that I hope will help. What do you think of this:

https://github.com/AOMediaCodec/libavif/commit/0ba2ca73919e376bb25d0cfb265f8aca5c8faa85

The intent here is to allow people to do `#if AVIF_VERSION >(whatever number is the current release tag)`, as the master branch should always be a _little bit_ larger than the most recent release tag. I think this solves the use case you had. Thoughts?

**Comment by novomesk** [comment]
I think it is good idea.
