### ISSUE TITLE
Example apps don't compress enough

### ISSUE THREAD

**Issue by jrmuizel** [AOMediaCodec/libavif#4]
Compressing 
![wollerau-B](https://user-images.githubusercontent.com/332653/60911383-fdc2db80-a250-11e9-8c2b-e9ed4de01f4a.png)
with "-q 63" gives a file that's 55700 bytes (larger than 50% quality JPEG). It would be nice to be able compress to smaller file sizes.

**Comment by vi** [comment]
Quality range of 42 to 63 tends to give me exactly the same output file.

**Comment by vi** [comment]
Patch for enabling low-quality mode:

```diff
diff --git a/src/codec_aom.c b/src/codec_aom.c
index 019865c..22241a8 100644
--- a/src/codec_aom.c
+++ b/src/codec_aom.c
@@ -284,6 +284,7 @@ static avifBool encodeOBU(avifImage * image, avifBool alphaOnly, avifEncoder * e
         cfg.rc_max_quantizer = 0;
     } else {
         cfg.rc_max_quantizer = quality;
+        cfg.rc_min_quantizer = quality;
     }
 
     uint32_t encoderFlags = 0;
```

**Comment by joedrago** [comment]
I agree with this patch that both the min and max quantizers should be adjustable by the user of the library, so I've just exposed them directly (and abandoned the confusing term "quality" here). 

I'll probably bump the version soon, but latest in master uses minQuantizer (`--min`) and maxQuantizer (`--max`) instead of "quality".
