### ISSUE TITLE
Add more aom-specific advanced options?

### ISSUE THREAD

**Issue by linkboyx** [AOMediaCodec/libavif#548]
Hi, thanks for your great job! 
I'm now developing on Android with libavif, and hope to speed up the aom-based avif encoder on the phone. I found that some aom-specific options(like enable-angle-delta , ...) could reduce the encoding time (may loss efficiency or decrease qulity, I guess so but not tested yet).  
Since I lack of codec knowledge and have no ideas about which options are critical, so could you please pick  some key options for encoding speed in AOM and add them into avif settings?. I will test them on the tradeoff between efficiency and speed on the phone.
Thanks a lot!

**Comment by joedrago** [comment]
Perhaps @wantehchang can offer some insight on this, but I imagine any option that is useful for images (AVIF) he's already made available.

**Comment by linkboyx** [comment]
Thanks for you reply!
On my desktop, if some aom options were closed, the encoding speed can increase from 1.7 fps to 2.9 fps.   For example, if i set --enable-angle-delta=0 only, time decrease 80ms, but file size increases 6KB. 
I also care about the RAM, but have not found any options could reduce RAM.  But there is a huge RAM reduction from ~500MB(aom 2.0.2) to ~110MB(aom 2.1.0/3.0.0) on a 1080P image.

**Comment by wantehchang** [comment]
Hi linkboyx,

Thank you for your interest in using the libaom-based AVIF encoder on Android. Our team uses the following `avifenc` options to encode AVIF images without alpha channels (please replace `T` and `QP` with suitable values):

`avifenc --speed 6 --jobs T -y 420 --min 0 --max 63 -a end-usage=q -a cq-level=QP happy_dog.jpg happy_dog.avif `

Replace `T` with the number of worker threads you want the encoder to use.

Replace `QP` with a value in the range from 0 (best quality) to 63 (worst quality).

You can also try `-a tune=ssim` with a high quality (i.e., a low `QP` value).

Please use a recent stable snapshot from the master branch of libaom. (The `v3.0.0-rc1` tag does not have the new all-intra encoding mode.) Note that the master branch of libaom is not fully "continuously releasable" because the full test suites are run once a day. So you need to run `test_libaom` on a snapshot that you are considering to use. You can try https://aomedia.googlesource.com/aom/+/41fd15c9c999e03247ba88da2c2f54c54a4c4488.

Regarding libaom 2.0.2: Although libaom 2.0.2 is the latest official libaom release, it is based on a release branch that's already 10 months old. I tried to back-port the memory usage reduction that you observed to that release branch but gave up. So I suggest using `v3.0.0-rc1` (or `v3.0.0` when it is released). But to benefit from the latest encoding speedup you will need to use a snapshot from the master branch.

**Comment by linkboyx** [comment]
> Hi linkboyx,
> 
> Thank you for your interest in using the libaom-based AVIF encoder on Android. Our team uses the following `avifenc` options to encode AVIF images without alpha channels (please replace `T` and `QP` with suitable values):
> 
> `avifenc --speed 6 --jobs T -y 420 --min 0 --max 63 -a end-usage=q -a cq-level=QP happy_dog.jpg happy_dog.avif `
> 
> Replace `T` with the number of worker threads you want the encoder to use.
> 
> Replace `QP` with a value in the range from 0 (best quality) to 63 (worst quality).
> 
> You can also try `-a tune=ssim` with a high quality (i.e., a low `QP` value).
> 
> Please use a recent stable snapshot from the master branch of libaom. (The `v3.0.0-rc1` tag does not have the new all-intra encoding mode.) Note that the master branch of libaom is not fully "continuously releasable" because the full test suites are run once a day. So you need to run `test_libaom` on a snapshot that you are considering to use. You can try https://aomedia.googlesource.com/aom/+/41fd15c9c999e03247ba88da2c2f54c54a4c4488.
> 
> Regarding libaom 2.0.2: Although libaom 2.0.2 is the latest official libaom release, it is based on a release branch that's already 10 months old. I tried to back-port the memory usage reduction that you observed to that release branch but gave up. So I suggest using `v3.0.0-rc1` (or `v3.0.0` when it is released). But to benefit from the latest encoding speedup you will need to use a snapshot from the master branch.

Thank you so much for your sharing! I will try the new commit on master branch of libaom as you suggested. 

At the beginning, I used the avif settings just like the avifenc options you shared, with higher --speed setting. Since higher encoding speed is desired, I tried to look at libaom and found that some libaom's options are not included in libavif's adavanced options. 

Although I dont understand each libaom's option very much, I did some tests and the results showed that if some libaom's features are disabled, the encoding speed will increase, such as --enable-angle-delta=0.

So from your professional perspective, would you consider  to add more libaom's feature options into libavif for more flexible settings supporting different preferences? Or just keeping those libaom's feature options as default is a better choice?
Thank you.

**Comment by linkboyx** [comment]
If you think it is reasonable to add some libaom's options but have no time to do that, we can pick some libaom's options which related to encoding speed and commit a PR if you dont mind.  @wantehchang

**Comment by wantehchang** [comment]
Hi linkboyx,

I am sorry I missed your reply.

I recommend using libavif speeds 0..6 if you want good quality. (Currently libavif speed 7 is the same as speed 6.) Speeds 7-10 use libaom's real-time usage mode, so quality or file size will be sacrificed.

Now that libaom v3.0.0 has been released, we can change libavif/src/codec_aom.c to use the new aom_codec_set_option() function:
https://aomedia-review.googlesource.com/c/aom/+/126302

This function will allow you to pass any libaom encoder options to libavif as codec-specific options. To detect the presence of the aom_codec_set_option() function at compile time, use this test:

`#if AOM_CODEC_ABI_VERSION >= (6 + AOM_IMAGE_ABI_VERSION)`

It will be easier if I write this pull request. But you are welcome to give it a try.

As for experimenting with libaom encoder options like --enable-angle-delta=0: you can certainly try them. The effects of some of the encoder options are difficult to understand unless you are familiar with libaom encoder's internals. Since the reason you want to try other libaom encoder options seems to be encoding speed, I suggest you try the HEAD of libavif with a recent libaom commit such as 41fd15c9c999e03247ba88da2c2f54c54a4c4488 and see if that is fast enough for you.

**Comment by linkboyx** [comment]
Hi @wantehchang :

Since speed is our key requirement,  we always use realtime mode( speed 8 ~ 10). 

We have used libaom v3.0.0, and no big improvement on speed is observed rather than v3.0.0-rc1. (I guess that the commit 41fd15c9c999e03247ba88da2c2f54c54a4c4488 was cherry-picked by v3.0.0 ?)

We notice that libaom v3.0.0 added a faster speed option "9",  and seems not be introduced in libavif yet.

We expect that the faster speed 9  and the new 'aom_codec_set_option()' function you mentioned will be used in libavif soon.  Maybe in next Release Tag ? :)

Thank you very much for your reply and work!!

**Comment by wantehchang** [comment]
Hi linkboyx,

I wrote a pull request to use the new aom_codec_set_option() function if it is available:
https://github.com/AOMediaCodec/libavif/pull/567

Please try it.

libaom v3.0.0 is very similar to v3.0.0-rc1. That is why you did not observe any improvement on encoding speed.

Commit 41fd15c9c999e03247ba88da2c2f54c54a4c4488 is a recent snapshot of libaom's master branch. It is not in libaom v3.0.0. Actually, I now recommend a newer stable snapshot of libaom's master branch: commit 0a5da45c7f942908974f5ab8e107c9fa82048ae7. This is from last Thursday night.

I will look into using libaom's new speed 9. Since libavif needs to support various versions of libaom, I will need to detect (at compile time or at run time) if libaom speed 9 is available.

**Comment by wantehchang** [comment]
Hi linkboyx,

A good way to speed up encoding is to use multiple tiles with multiple threads. The tiles should not be too small. A good rule of thumb is that the tiles should not be smaller than roughly 512x512. In AV1, the number of tiles per row and the number of tiles per column must be a power of 2, so you actually specify the log2 of tiles per row and log2 of tiles per column.

**Comment by linkboyx** [comment]
Hi, @wantehchang !

Thanks for your rapid response!

I will try the new commit  using 'aom_codec_set_option()' and  the commit of AOM you suggested!  :)

We tested the new speed 9 of libaom but no big acceleration observed than speed 8.

Now we set the tiles to 2^1 for cols and 2^0 for rows for processing 1080P image. Maybe the phone's CPU has limited parallel computation, there is no more encoding time saved but less effeciency on file size when we set to 2^2 for cols and 2^1 for rows, in which each tile is closed to 512x512.

Any idea you suggested will be much appreciated.

**Comment by wantehchang** [comment]
Hi linkboyx,

To use the new speed 9 of libaom, you need to apply a patch like the following to libavif and use libavif speed 10:

```
diff --git a/src/codec_aom.c b/src/codec_aom.c
index 6b71ceb..7b50287 100644
--- a/src/codec_aom.c
+++ b/src/codec_aom.c
@@ -494,9 +494,9 @@ static avifResult aomCodecEncodeImage(avifCodec * codec,
         // Speed  5: GoodQuality CpuUsed 5
         // Speed  6: GoodQuality CpuUsed 6
         // Speed  7: GoodQuality CpuUsed 6
-        // Speed  8: RealTime    CpuUsed 6
-        // Speed  9: RealTime    CpuUsed 7
-        // Speed 10: RealTime    CpuUsed 8
+        // Speed  8: RealTime    CpuUsed 7
+        // Speed  9: RealTime    CpuUsed 8
+        // Speed 10: RealTime    CpuUsed 9
         unsigned int aomUsage = AOM_USAGE_GOOD_QUALITY;
         // Use the new AOM_USAGE_ALL_INTRA (added in https://crbug.com/aomedia/2959) for still
         // image encoding if it is available.
@@ -511,7 +511,7 @@ static avifResult aomCodecEncodeImage(avifCodec * codec,
                 aomCpuUsed = AVIF_CLAMP(encoder->speed, 0, 6);
             } else {
                 aomUsage = AOM_USAGE_REALTIME;
-                aomCpuUsed = AVIF_CLAMP(encoder->speed - 2, 6, 8);
+                aomCpuUsed = AVIF_CLAMP(encoder->speed - 1, 7, 9);
             }
         }
 
```

Since libaom is an AV1 video encoder, it is possible that the speedup of speed 9 is more pronounced when you encode a video, which has not only key frames but also inter frames. (An AVIF still image contains just a single AV1 key frame.) This is just my speculation though.

Your first tile setup (2^1 for cols and 2^0 for rows) for 1080p images looks very reasonable. That setup has two tiles, so you should use two worker threads. Current ARM CPUs have the big.LITTLE architecture. It is possible that you get the most speedup when you use as many worker threads as the number of big cores, and using more worker threads than the number of big cores (which is definitely the case in your second tile setup) may not be profitable. (I would not be surprised if the multithreaded code in libaom assumes all cores are equal.)

**Comment by wantehchang** [comment]
Hi linkboyx,

To use a stable snapshot (e.g., commit 0a5da45c7f942908974f5ab8e107c9fa82048ae7) from the master branch of libaom, apply a patch like the following to libavif:

```
diff --git a/ext/aom.cmd b/ext/aom.cmd
index 39d20c9..6fd6392 100755
--- a/ext/aom.cmd
+++ b/ext/aom.cmd
@@ -8,9 +8,10 @@
 : # If you're running this on Windows, be sure you've already run this (from your VC2019 install dir):
 : #     "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvars64.bat"
 
-git clone -b v3.0.0 --depth 1 https://aomedia.googlesource.com/aom
+git clone https://aomedia.googlesource.com/aom
 
 cd aom
+git checkout 0a5da45c7f942908974f5ab8e107c9fa82048ae7
 mkdir build.libavif
 cd build.libavif
 
```

**Comment by linkboyx** [comment]
Thank you so much for your detailed instruction,  @wantehchang :+1:
