### ISSUE TITLE
Add vcpkg integration

### ISSUE THREAD

**Issue by HappySeaFox** [AOMediaCodec/libavif#560]
It would be just great to have libavif available in vcpkg.

https://github.com/microsoft/vcpkg

**Comment by 1480c1** [comment]
You may wish to ask upstream instead, although it seems it was asked before https://github.com/microsoft/vcpkg/issues/9741

**Comment by smoked-herring** [comment]
The problem here is who will maintain the package. No one will do that as good (timely etc.) as the original author. Basically what I'm proposing is to start packaging and supporting libavif as a vcpkg port on a continuous basis.

**Comment by HappySeaFox** [comment]
Libavif is now available in vcpkg. See https://github.com/microsoft/vcpkg/pull/18244

**Comment by wantehchang** [comment]
Hi Dmitry,

Thank you very much for creating a package for libavif in vcpkg!

I took a look at your package files. I have a question and a suggestion.

1. Re: `disable-source-utf8.patch`: Why did you need to remove the `/source-charset:utf-8 /execution-charset:us-ascii` compiler flags?
2. If the dav1d library is available as a package in vcpkg, I suggest using dav1d as the decoder. You can then optionally add` -DAVIF_CODEC_AOM_DECODE=OFF` to use libaom for encoding only.

**Comment by HappySeaFox** [comment]
Hi! 😀

1. Vcpkg enforces /utf8 msvc flag which conflicts with the two flags in question. If you have a better idea how to fix the conflict please let me know
2. Unfortunately, Dav1d codec currently cannot be installed in vcpkg  because of the following issue https://github.com/microsoft/vcpkg/issues/16986

**Comment by wantehchang** [comment]
Hi Dmitry,

I think it is fine to compile libavif with the `/utf-8` flag instead of the `/source-charset:utf-8 /execution-charset:us-ascii` flags. The `/utf-8` flag is equivalent to `/source-charset:utf-8 /execution-charset:utf-8`. So the difference is whether the execution charset is us-ascii or utf-8.

As long as someone or some buildbot compiles libavif regularly with `/execution-charset:us-ascii`, we will be able to detect any non-ASCII characters in our error messages.

@tongyuantongyu: Is my analysis correct?
