### ISSUE TITLE
Ignore incompatible libyuv

### ISSUE THREAD

**Issue by smoked-herring** [AOMediaCodec/libavif#593]
Hi!

avif enables libyuv support even if the installed libyuv version is not compatible or outdated which leads to compilation errors:

```
reformat_libyuv.c(113): error C2065: 'kYuv2020Constants': undeclared identifier
```

It would be great to add more tests to check if the installed libyuv is compatible and enable/disable its support appropriately.
It would be also great to add an option to disable libyuv explicitly like `cmake -DAVIF_ENABLE_LIBYUV=OFF <...> ..`

**Comment by joedrago** [comment]
I see that you've opened PR #594 to address this, so I'll have a discussion there with you.

**Comment by smoked-herring** [comment]
[install-x64-windows-dbg-out.log](https://github.com/AOMediaCodec/libavif/files/6313906/install-x64-windows-dbg-out.log)

**Comment by joedrago** [comment]
_Side note: I misspoke in #594 when I said libyuv was unversioned. There most certainly is a `version.h` which is regularly incremented, and should be sufficient for these checks. I doesn't matter that there aren't official tagged releases._

Alright, I've taken a shot at fixing this. I thought from your explanation that I could get away with just avoiding some "newer" constants such as the BT2020 Matrix, but it turns out every function `libavif` currently calls (`I*Matrix()` functions) were all exposed in the same commit/version as those matrices: Version `1755`.

I've updated libavif's `Findlibyuv.cmake` to harvest the version number from `libyuv/version.h`, and if it is `<1755`, I print a message similar to the one in your PR ("libyuv (...) found, but is too old; libyuv-based fast paths disabled."). Let me know if this works for you. It is going through the builders now.

**Comment by smoked-herring** [comment]
@joedrago Thanks for the quick fix, it definitely works for me.
