### ISSUE TITLE
abort() when allocate failed ?

### ISSUE THREAD

**Issue by linkboyx** [AOMediaCodec/libavif#611]
Hi, @joedrago 

We are using libavif in our app. We found in code that if memory allocation failed, it will abort directly, which will crash our app.

Shall we consider handling this in other ways? 

Thank you very much.

in mem.c file.
`void * avifAlloc(size_t size)
{
    void * out = malloc(size);
    if (out == NULL) {
        abort();
    }
    return out;
}`

**Comment by joedrago** [comment]
Hello!

This has been discussed before, and I'm not against an eventual refactoring of libavif to handle out-of-memory gracefully. However, until such a refactor is complete, the abort() here protects us from unexpected behavior in the case where we run out of memory.

Perhaps a good starting approach could be to identify the likely places where out-of-memory is most likely (large allocations of pixel memory, sample memory, etc) and gracefully returning a new `avifResult` for those. This would cover the most common cases, and would open a path to eventually being able to remove the `abort()`. I'll look into this soon and let you know.

**Comment by wantehchang** [comment]
Hi linkboyx,

I just wanted to confirm with you that you discovered this issue by code inspection, rather than an actual memory allocation failure in libavif. If you encountered an actual memory allocation failure, please let us know which avifAlloc() call failed, so that Joe can make sure to handle the failure of that avifAlloc() call.

**Comment by linkboyx** [comment]
Thank you for replies! @joedrago @wantehchang 

Yes, we discoverd this issue by code inspection, and we have not encountered an actual memory failure or app crash. We just worry about that since our app may used on some low-level phones.  Maybe we should constarin the image size?

and i have another question,  does Avif support region decode?  which is useful when the image is too big.

Thanks!

**Comment by wantehchang** [comment]
Hi linkboyx,

libavif constrains the image size (the pixel count = width * height) to 2^28.

```
// A maximum image size to avoid out-of-memory errors or integer overflow in
// (32-bit) int or unsigned int arithmetic operations.
#define AVIF_MAX_IMAGE_SIZE (16384 * 16384)
```

This maximum image size was chosen to avoid common integer arithmetic overflow. Joe wrote a patch before to allow libavif users to further constrain the image size (or remove the image size limit), but apparently that patch was not checked in.

libavif does not support region decode, because none of the AV1 decoders (dav1d, libaom, and libgav1) support it.

**Comment by linkboyx** [comment]
Hi, @wantehchang 

the 6000 * 8000 size image is the common issue which we are most concerned about, it's far less than the constrain.

if the big image is encoded in many tiles, maybe libavif could decode it according to a given region?  Just a idea, that is so complicated.

I'm going to close this issue. If we really have an OOM,  i will post it here.

Thank you all!

**Comment by joedrago** [comment]
As a note, `avifDecoderParse()` does not invoke any AV1 decoding, nor does it allocate any pixel storage. you should be able to run this and (if it returns OK) see how big the image will be in advance. you could use this and the available amount of memory you have left as a hint to whether or not you want to preemptively block the rest of the decode.
