### ISSUE TITLE
cicp reference values

### ISSUE THREAD

**Issue by Lee-lithium** [AOMediaCodec/libavif#621]
Version: 0.9.0 (dav1d [dec]:0.8.2-0-gf06148e, aom [enc/dec]:3.1.0, rav1e [enc]:0.4.1 (v0.4.1))  
https://ci.appveyor.com/project/louquillio/libavif  
Sorry, my english is not good  
  
Hello, I try to use libavif 0.9.0 YCgCo implement on png image,  
on old version libavif i use --cicp 1/13/0, but this values can't useable on 0.9.0,  
what's values is best practice for YCgCo?(--cicp 1/13/8 or --cicp 2/2/8).  
  
> avifenc --min 6 --max 6 --minalpha 0 --minalpha 0 -d 10 -s 4 -j 12 --cicp 1/13/8 -a end-usage=q -a cq-level=6  
  
About cicp values, I read avif.h try to understand three raw values,  
but i still can't find too many information,  
could you teach some detail about three raw values?
  
> P = color primaries  
> T = transfer characteristics  
> M = matrix coefficients  
> https://github.com/AOMediaCodec/libavif/blob/master/include/avif/avif.h  

I only know 1/13/6 for YUV  
> --cicp 1/13/6 YUV

**Comment by joedrago** [comment]
> but this values can't useable on 0.9.0

Why not? MC=0 is still supported in avifenc v0.9.0.

> could you teach some detail about three raw values?

CICP is short for "Coding-independent code points for video signal type identification", which is the name of the standard **H.273**. The standard is free to read here:

https://www.itu.int/rec/T-REC-H.273-201612-I/en

This explains every value for CP (colourPrimaries), TC (transferCharacteristics), and MC (matrixCoefficients).

But as a quick explanation:

The third value (MC) determines how the YUV data inside of the file should be converted back to RGB. For many values of MC (1,5,6,9, etc), they are just providing specific coefficients for a standard conversion between YUV and RGB. For a few special MC values (0, 8, etc), they indicate a special type of packing, which probably isn't YUV at all.

0 means Identity, which means the RGB values weren't converted at all, but simply packed in the order GBR right into the planes. This makes for very inefficient encoding (as AV1 thinks in terms of luma and chroma), but allows for lossless encoding.

8 means YCgCo, which has different math than a typical YUV conversion. The details of this math are in the free standard PDF linked above.

**Comment by Lee-lithium** [comment]
Hello joedrago, Thanks for your reply,  
Sorry to reply you so late,  
  
On old version avifenc, if i use --cicp 1/13/0, avifenc will reset to 6 and display this message,  
```WARNING: matrixCoefficients may not be set to identity(0) when subsampling. Resetting MC to defaults.```  
but on new version avifenc, i can success pass different matrix coefficients(1/13/0, 1/13/8, 2/2/0, 2/2/8).   
  
I have some question about cicp and color precision loss when convert, Could you teach me?  
  
1. avifenc will use --cicp 2/2/6 when image have icc profile,  
If i want use --cicp x/x/8 ycgco convert on png rgb image,  
use --cicp 2/2/8 let avifenc decide, probably a best practice on avifenc?  
  
2. I want reduce color precision loss when convert,  
so i plan use ycgco(--cicp 2/2/8) on png rgb screen content image,  
but some image is already to jpeg yuv.  
If i use ycgco(--cicp 2/2/8) on jpeg yuv, probably can reduce color precision loss when convert?  
  
YUV(ycbcr)->RGB->ycbcr 444  
YUV(ycbcr)->RGB->ycgco 444  
  
```https://www.reddit.com/r/AV1/comments/jmteaf/avif_images_color_losschange/```  
```https://github.com/AOMediaCodec/libavif/pull/430```

**Comment by joedrago** [comment]
Note: I replied directly to the reddit link you offered 6 months ago, explaining the issues the user was seeing. I believe at the time, the user was simply using viewers that made assumptions about color range, not any issues with avifenc.

Setting the matrix coefficients to 0 (Identity) says that you _don't want to use YUV_, but that you just want to pack the RGB values directly into the planes (in the order GBR). It is currently the only way to truly achieve _lossless_ encoding at the same bit depth as the source image, but the file sizes will be much larger (sometimes larger than PNG, even). Unless you have a need for perfect storage of every pixel's values and are willing to have very large files in comparison, I don't recommend using MC=0.

If you are looking for high quality (but not _exactly lossless_), any of the other matrix coefficients will do just fine. The default is 6 because that uses BT601's coefficients, which is what JPEG uses, and is the default for most (SDR) YUV video as well. If your goal is to increase quality (but still be lossy), MC isn't the interesting setting. You should be adjusting the quantizers (`--min`, `--max`), or using some of the more advanced AOM quality settings. 

If you use an ICC profile, the first two values (color primaries and transfer characteristics) tend to output as `2/2` because the ICC profile overrides them after the pixels are decoded back to RGB, so they're not interesting here. `2/2` are Unspecified, and would be treated as SRGB (`1/13`) if the ICC profile wasn't present. 

Version 0.9.1 (released today) adds the support for using the YUV data in JPEG directly (from #430 that you linked). If you use `--yuv auto` and supply a JPEG as the source, it will use the YUV data directly.

**Comment by Lee-lithium** [comment]
Hello joedrago, Thanks for your reply  
About CICP values it is clear to me now,  
Thank you so much for your help joedrago :)  
  
I also find some CICP information on libavif comment.  
> https://github.com/AOMediaCodec/libavif/blob/bfc5acad3f987d05ec5221f702ceea466d2f81be/apps/avifenc.c#L860  
> // The final image has no ICC profile, the user didn't specify any CICP, and the source  
> // image didn't provide any CICP. Explicitly signal SRGB CP/TC here, as 2/2/x will be  
> // interpreted as SRGB anyway.  
  
> https://github.com/AOMediaCodec/libavif/blob/bfc5acad3f987d05ec5221f702ceea466d2f81be/apps/avifenc.c#L470  
> // By default, the color profile itself is unspecified, so CP/TC are set (to 2) accordingly.  
> // However, if the end-user doesn't specify any CICP, we will convert to YUV using BT601  
> // coefficients anyway (as MC:2 falls back to MC:5/6), so we might as well signal it explicitly.  
> // See: ISO/IEC 23000-22:2019 Amendment 2, or the comment in avifCalcYUVCoefficients()
