### ISSUE TITLE
Migrate Travis CI Build Flavors to GitHub CI

### ISSUE THREAD

**Issue by joedrago** [AOMediaCodec/libavif#630]
Travis CI appears to have run out of "free credits" and is in a negative state, and it looks like despite our project being public, free, and open source, they require payment (unless I'm mistaken).

Right now, our Travis builds have at least one flavor that neither of our other two CI (GitHub and AppVeyor) provide, which is the shared library build. This recently caused an issue with the new release (#629), so it is clear we need to remove this blindspot with Travis being unavailable.

I thin the best play right now is to migrate the shared library builds that we had in Travis over to to GitHub's CI. I'll probably do this myself at some point in the next week, unless @EwoutH or someone else wants to take a shot at it first.

**Comment by EwoutH** [comment]
To give some background: All major CI providers have a huge problems with people trying to mine crypto currencies on their free tier, which is why they all got much more limited in the past months. So not only it now wastes huge amounts of energy and contributes significantly to the global chip shortage, it now also is the main focus of lots of CI and DevOps engineers... I can get quite pissed about this.

See also: [Crypto miners are killing free CI](https://layerci.com/blog/crypto-miners-are-killing-free-ci/)

Back on this specific issue: I would suggest contacting Travis CI since they were very committed to FOSS in the past, but it [seems like it’s difficult](https://travis-ci.community/t/intending-to-use-travis-for-a-foss-project-forget-it/11406) to get in touch currently.

So that indeed leaves migrating to another CI provider for now. You can assign this issue to me if you want.

**Comment by joedrago** [comment]
Interesting info. I didn't realize that was going on, but it makes sense.

**Comment by vigneshvg** [comment]
@joedrago i believe we have moved to Github CI fully and have been relying on it heavily for quite some time now (it also includes stuff like testing AV2, android JNI, android tests on emulators).

I am marking this issue as completed. Please feel free to re-open if you think there is anything else that needs to be done for thi issue.

**Comment by wantehchang** [comment]
Vignesh: Thanks for closing this issue. Should we delete the .travis.yml file now?

**Comment by vigneshvg** [comment]
> Vignesh: Thanks for closing this issue. Should we delete the .travis.yml file now?

yes i believe we can, i will write a PR for that.
