### ISSUE TITLE
Animated transparent gif --> to --> avif 

### ISSUE THREAD

**Issue by petrich** [AOMediaCodec/libavif#738]
Hi There

is there any way to encode an animated transparent gif to avif? 

Thank you
Greetings Hans-Juergen Petrich

**Comment by joedrago** [comment]
I'm not against adding proper gif reading support to `avifenc` someday, but I figured since it was a sequence that we might be able to leverage `ffmpeg`, as (loosely) documented here:

https://github.com/AOMediaCodec/libavif/wiki/Sequences

I've made this work, but it has two caveats:

* ffmpeg support for `yuva444p` y4m piping was only added 29 days ago (!)
* My y4m `yuva444p` reading code had a bug :-/

I've opened a PR already to fix my bug here: https://github.com/AOMediaCodec/libavif/pull/740

With a very-recent ffmpeg (newer than 29 days) and an avifenc with this bugfix, this worked for me:

```
ffmpeg -i alrighty-then.gif -strict -1 -f yuv4mpegpipe -pix_fmt yuva444p - | avifenc --stdin --fps 12 alrighty-then.avif
```
[alrighty-then.zip](https://github.com/AOMediaCodec/libavif/files/7028013/alrighty-then.zip)

314kb to 46kb! Not bad!

(I realize now I should have tried with a _transparent_ gif, but I'm verifying that alpha is coming through the pipe, so I'm confident this will work with alpha too.)

**Comment by petrich** [comment]
Hi, 

Great! Thank you very much. 

I testet it (with the newest ffmpeg version and libavif with #740 ) with an animated transparent gif... works all fine now.

Greetings
