### ISSUE TITLE
Was the major version bump intentional?

### ISSUE THREAD

**Issue by hmaarrfk** [AOMediaCodec/libavif#799]
It seems that from going between version 0.9.2 -> 0.9.3 the library file went from 12 - >13 

https://github.com/AOMediaCodec/libavif/commit/ac76fe0d16a255bccefff5bdfddd865742176d85

Was this intentional? Seems strange that for a "patch" release, the SO version's major version would change.

Thanks for your help.

**Comment by carterbox** [comment]
@hmaarrfk, I found [this article from autotools](https://autotools.io/libtool/version.html) explaining why the ABI (so version) should be versioned separately from the API (package version). The short explanation is that something like switching the order of fields in a struct is an ABI breaking change, but would be a patch for the API. Have separate versions for ABI and API allows programmers to immediately see if they need just recompile/link or to edit their own code and recompile/link.

**Comment by wantehchang** [comment]
@hmaarrfk @carterbox: I am sorry for the very late reply. I was out of the office when this issue was opened and this somehow fell through the cracks.

There are two parts to the answer to your question.

1. When I created the 0.9.3 release, I knew about the change to the order of fields in the public avifDecoder struct. That is why I bumped the `LIBRARY_VERSION_MAJOR` variable in libavif's CMakeLists.txt. But I think it was an oversight for me to bump only the `AVIF_VERSION_PATCH` macro in avif/avif.h.

2. Ideally we should bump the AVIF_VERSION_MAJOR macro when there is an ABI breaking change. But we are making an exception right now because we have not frozen the libavif API. This is why the API version is 0.x.y -- the 0 major number indicates the API is still evolving. So, I think I should have named that version 0.10.0 instead of 0.9.3, but it could not be 1.0.0. This means before we reach the 1.0.0 milestone, we will continue to see the ABI and API versions out of sync.

**Comment by wantehchang** [comment]
@hmaarrfk: I forgot to say I will be more mindful of this issue in the future. Thank you for reporting this issue.

**Comment by hmaarrfk** [comment]
understood.

we will take it into consideration in packaging.

**Comment by hmaarrfk** [comment]
Just circling back onto this. Are you planning on having ABI for future patch releases starting with 0.10.0 or should we plan on waiting for the 1.0.0 release?

**Comment by wantehchang** [comment]
Hi Mark,

These 0.x.y version numbers suggest that incompatible changes to the ABI are allowed. So ABI compatibility guarantee will start with version 1.0.0.

The public structs in the avif.h header such as `avifDecoder` and `avifEncoder` will need some work (such as adding a version or struct-size field) to allow us to extend them in compatible ways.

**Comment by hmaarrfk** [comment]
Totally understood..

Thank you for confirming
