### ISSUE TITLE
Building AOM with Visual Studio 2019 in Release Mode

### ISSUE THREAD

**Issue by ppersits** [AOMediaCodec/libavif#861]
How would I build aom.lib with Visual Studio 2019 on Windows in release mode? I tried

cmake c:\path\aom-main -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DENABLE_DOCS=0 -DENABLE_TESTS=0 -DCONFIG_AV1_ENCODER=0
cmake --build .

But the switch -DCMAKE_BUILD_TYPE=Release does not seem to have any effect. The result of the above is still the folder Debug/aom.lib (not Release/aom.lib as once would expect) and the size of the output file is about the same regardless of whether this switch is present.

**Comment by joedrago** [comment]
I believe this is an idiosyncracy with CMake and its interaction with Visual Studio, and nothing specific to libavif. The Visual Studio generator for CMake generates _all_ build types (ignoring `CMAKE_BUILD_TYPE`), as they expect you to choose the build type in a pulldown menu inside of VS before choosing build. In order to choose a Release build when asking CMake to run a VS build from the commandline, you must use the `--config` option on the cmake build commandline, such as:

    cmake --build --config Release

Give that a shot. 

For what its worth, if you plan to build exclusively on the commandline and never directly Visual Studio, I recommend using a lighter weight / faster commandline build system like `Ninja`. Non-VS generators (such as `Ninja`) honor `CMAKE_BUILD_TYPE` the way you were expecting it to work.

**Comment by ppersits** [comment]
Joe,

Can I please bother you again for a sec? I tried your AVIF decoder and encoder code samples together with the AOM library: I opened an AVIF file and then saved it also as AVIF.

The result was very puzzling. First of all, the encoding took forever. Secondly the output image was almost 10 times larger (82KB original file, 694KB output file.) I am attaching both files.

How would you explain that? Thanks a lot!

Peter Persits
Persits Software, Inc.
http://www.persits.com

**Comment by joedrago** [comment]
I don't see any attachments?

**Comment by joedrago** [comment]
Even without attachments, my wild guess on this issue is simply that you haven't configured your `avifEncoder` instance for what kind of output quality you want. By default, it chooses quantization of min:0 and max:0, which will make a very large, almost-lossless encode. There's a block that looks like this in the `avif_example_encode` example:

    encoder = avifEncoderCreate();
    // Configure your encoder here (see avif/avif.h):
    // * maxThreads
    // * minQuantizer
    // * maxQuantizer
    // * minQuantizerAlpha
    // * maxQuantizerAlpha
    // * tileRowsLog2
    // * tileColsLog2
    // * speed
    // * keyframeInterval
    // * timescale

This is your hint to read these settings in `avif.h` and decide for yourself (or allow an enduser to configure) these options. The (fairly opinionated and arbitrary) defaults that `avifenc` chooses can be found at the top of `avifenc.c`'s `main()` function.

**Comment by ppersits** [comment]
You are my savior! Thanks a lot! Now it is working fast and the images are small!

Peter Persits
Persits Software, Inc.
http://www.persits.com

**Comment by wantehchang** [comment]
Marked the issue fixed.

**Comment by ppersits** [comment]
Joe,

Can I please bother you one more time.

I am setting the maxQuantizer/minQuantizer/maxQuantalpha/maxQuantAlpha parameters to 0, which should mean lossless compression, and speed to 10.

I am converting this simple jpeg (attached, original.jpg) to AVIF but the result is unsatisfactory. The image is much larger than the original and most importantly, the quality totally sucks (see atttached, out.avif).

What am I missing? I am using the AOM library as my encoder.

Thanks as always.


Peter Persits
Persits Software, Inc.
http://www.persits.com

**Comment by ppersits** [comment]
Please disregard, sorry to have bothered you. But I may have more questions in the near future if you don’t mind.

Thanks as always.

Peter Persits
Persits Software, Inc.
http://www.persits.com
