### ISSUE TITLE
avifenc: Input Jpg with rotation in EXIF is not propagated to AVIF file

### ISSUE THREAD

**Issue by FrankGalligan** [AOMediaCodec/libavif#996]
Steps to reproduce:
1) Build avifenc
2) avifenc happy_dog.jpg out.avif
3) View out.avif

out.avif should render in portrait mode with the dog sitting up. Instead out.avif renders in landscape mode with the dog rotated 90 degrees.

![happy_dog](https://user-images.githubusercontent.com/13208870/181127621-b155abda-83d6-4c65-871e-9cb02c20ceb8.jpg)

**Comment by joedrago** [comment]
To pull this off, I believe the following would have to happen:

* We'd need a new function that would take an Exif payload an `avifImage*` and would adjust its transformationss based on what it found. Ideally this wouldn't require depending on an external library like `libexif` (if we could just pull out a few tiny bits of data), but it wouldn't be the end of the world if the apps themselves depended on it (not the libavif library).

* Both the JPEG and PNG read paths would have to be updated to harvest the Exif payload from the file (if present), and would have to invoke this function.

* Related commandline arguments such as `--exif` or `--imir`  would have to "win"/override whatever was in the source data, and we'd probably want to add a new argument like `--ignore-exif`, akin to `--ignore-icc`.

I haven't ever attempted to parse Exif before (including via libexif), so I feel like the scope of this task heavily depends on the effort required to make the initial function I described, including potentially incorporating a new dependency if necessary. Everything else is just sugar on top.

**Comment by jzern** [comment]
In WebP we treat exif and icc as binary blobs [1][2] and leave it to the application. In Chrome, though, we only use icc.
In AVIF's case this might be different because the format offers rotation support.

[1] https://chromium.googlesource.com/webm/libwebp/+/refs/tags/v1.2.3/imageio/jpegdec.c#158
[2] https://chromium.googlesource.com/webm/libwebp/+/refs/tags/v1.2.3/imageio/pngdec.c#136

**Comment by joedrago** [comment]
Yes, it'd be simpler if we just treated Exif like ICC here and migrated the raw payload over (and it worked), but one of the standards AVIF derives from (either HEIF or MIAF?) says that the renderer should not honor the orientation in Exif, only the orientation defined by transformations in `irot`/`imir` (etc).

I didn't want to offer simply migrating the raw Exif payload as it won't solve the ultimate problem of seeing it correctly in Chrome, although a side effect of implementing this correctly will be to have the payload migration come along for the ride.

**Comment by FrankGalligan** [comment]
If we could add support without adding a dependency on libexif, that would be ideal.

**Comment by novomesk** [comment]
I think there could be two approaches:

1.)
Parse Exif metadata from source, set irot/imir correspondingly and copy Exif as-si to output AVIF. Viewer will display the AVIF image according irot/imir the same way as original is displayed according Exif.

2.)
Parse Exif metadata from source and rotate source image according orientation in Exif. Clear orientation in Exif, set new dimentions in Exif, clear Exif thumbnail (it also could be rotated), clear or remove other metadata affected by potential rotation. Write unrotated AVIF (no imit/irot) with updated Exif (no rotation).

In both approaches, the orientation in AVIF and metadata are in sync. While specification says, that orientation in format has preference to the orientation in Exif metadata, application developers naturally expect that they are equal (so that metadata accurately fits the image), otherwise they are confused.

Scenario 1 is something similar what JPEG XL `cjxl` utility is doing when converting JPG to JXL. They also store orientation in JXL bitstream (which was preference too over orientation in metadata like in AVIF) and I believe they probably keep Exif metadata unchanged, because from some JXL you can reconstruct the original JPG source file.
Scenario 2 is something what happens when you open rotated JPG in GIMP 2.99 (not 2.10.x) and then export AVIF with metadata. Metadata gets edited there.

**Comment by y-guyon** [comment]
Note: `heif-enc` from https://github.com/strukturag/libheif/commit/f3f71c8d67ca3265b76c782e48eb6fc68950a0a6 does not import Exif metadata or orientation when converting to AVIF or HEIC either.

**Comment by y-guyon** [comment]
Fixed through https://github.com/AOMediaCodec/libavif/pull/1088 and https://github.com/AOMediaCodec/libavif/pull/1099.

`avifenc dog.jpg dog.avif` and opening `dog.avif` in Chrome renders it in portrait mode (the following image has a .jpg extension to be accepted by GitHub but is actually an AVIF file):
![dog avif](https://user-images.githubusercontent.com/51164219/191197240-bfb748d0-c9be-45ee-8cce-51bcff417725.jpg)

**Comment by novomesk** [comment]
Thank you for implementing this! It is important feature.
